import { SERVICES } from '../supported-service/services/iServiceList';
export enum TokenModule {
  DASHBOARD = 'DASHBOARD',
  VERIFIER = 'VERIFIER',
  APP_AUTH = 'APP_AUTH',
}
export const KYC_ACCESS_MATRIX = {
  [TokenModule.DASHBOARD]: [
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_CREDIT,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_CREDIT,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_WEBHOOK_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_WEBHOOK_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.UPDATE_WEBHOOK_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.DELETE_WEBHOOK_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_USAGE,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_WIDGET_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_WIDGET_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.UPDATE_WIDGET_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_VERIFIED_USER,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_ANALYTICS,
  ],
  [TokenModule.VERIFIER]: [
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_SESSION,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_USER_CONSENT,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_PASSIVE_LIVELINESS,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_DOC_OCR,
    SERVICES.CAVACH_API.ACCESS_TYPES.CHECK_LIVE_STATUS,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_WIDGET_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_USER_CONSENT,
  ],
  [TokenModule.APP_AUTH]: [
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_SESSION,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_USER_CONSENT,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_PASSIVE_LIVELINESS,
    SERVICES.CAVACH_API.ACCESS_TYPES.WRITE_DOC_OCR,
    SERVICES.CAVACH_API.ACCESS_TYPES.CHECK_LIVE_STATUS,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_WIDGET_CONFIG,
    SERVICES.CAVACH_API.ACCESS_TYPES.READ_USER_CONSENT,
  ],
};
export const SSI_ACCESS_MATRIX = {
  // will modify its access later. Assigning ALL for the time being
  [TokenModule.DASHBOARD]: [SERVICES.SSI_API.ACCESS_TYPES.ALL],
  [TokenModule.VERIFIER]: [SERVICES.SSI_API.ACCESS_TYPES.ALL],
  [TokenModule.APP_AUTH]: [SERVICES.SSI_API.ACCESS_TYPES.ALL],
};
export const QUEST_ACCESS_MATRIX = {
  [TokenModule.DASHBOARD]: [],
  [TokenModule.VERIFIER]: [],
  [TokenModule.APP_AUTH]: [SERVICES.QUEST.ACCESS_TYPES.VERIFY_USER],
};
